In [41]:
import numpy as np
import seaborn as sns
import pandas as pd

df = sns.load_dataset('tips')

In [3]:
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
print(df.shape)
print(df.columns)

(244, 7)
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [15]:
categorical = df.select_dtypes(include = "object").columns
print(categorical)

Index([], dtype='object')

In [14]:
numerical = df.select_dtypes(exclude = "object").columns
print(numerical)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [9]:
df['sex'] = df['sex'].astype('category')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [16]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [18]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [22]:
df[df['tip'] > 3]

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
219       30.14  3.09  Female    Yes  Sat  Dinner     4
221       13.42  3.48  Female    Yes  Fri   Lunch     2
232       11.61  3.39    Male     No  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3

[98 rows x 7 columns]

In [26]:
df[(df['tip'] > 3) & (df['sex'] == 'Male')]

     total_bill   tip   sex smoker  day    time  size
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
7         26.88  3.12  Male     No  Sun  Dinner     4
9         14.78  3.23  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
206       26.59  3.41  Male    Yes  Sat  Dinner     3
211       25.89  5.16  Male    Yes  Sat  Dinner     4
212       48.33  9.00  Male     No  Sat  Dinner     4
232       11.61  3.39  Male     No  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3

[66 rows x 7 columns]

In [29]:
df.sort_values('tip', ascending = False)

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
..          ...    ...     ...    ...   ...     ...   ...
0         16.99   1.01  Female     No   Sun  Dinner     2
236       12.60   1.00    Male    Yes   Sat  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
67         3.07   1.00  Female    Yes   Sat  Dinner     1
92         5.75   1.00  Female    Yes   Fri  Dinner     2

[244 rows x 7 columns]

In [32]:
df.sort_values(['tip', 'total_bill'], ascending = [False, True])

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
..          ...    ...     ...    ...   ...     ...   ...
0         16.99   1.01  Female     No   Sun  Dinner     2
67         3.07   1.00  Female    Yes   Sat  Dinner     1
92         5.75   1.00  Female    Yes   Fri  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
236       12.60   1.00    Male    Yes   Sat  Dinner     2

[244 rows x 7 columns]

In [34]:
df.groupby('sex', observed = False)['tip'].mean()

sex
Male      3.089618
Female    2.833448
Name: tip, dtype: float64

In [35]:
df.groupby('sex', observed = False)['total_bill'].mean()

sex
Male      20.744076
Female    18.056897
Name: total_bill, dtype: float64

In [39]:
df.groupby('day', observed = False)['total_bill'].max()

day
Thur    43.11
Fri     40.17
Sat     50.81
Sun     48.17
Name: total_bill, dtype: float64

In [40]:
df.groupby('day', observed = False)['total_bill'].min()

day
Thur    7.51
Fri     5.75
Sat     3.07
Sun     7.25
Name: total_bill, dtype: float64

In [44]:
df.groupby(['day', 'sex'], observed = True)['total_bill'].mean()

day   sex
Thur  Male      18.714667
      Female    16.715312
Fri   Male      19.857000
      Female    14.145556
Sat   Male      20.802542
      Female    19.680357
Sun   Male      21.887241
      Female    19.872222
Name: total_bill, dtype: float64

In [48]:
df[df['sex'] == 'Female']['tip'].mean().item()

2.8334482758620685

In [49]:
df[df['sex'] == 'Male']['tip'].max()

10.0

In [55]:
df[df['tip'] > 5]['total_bill'].count().item()

18

In [74]:
df.groupby(['sex', 'time'], observed = True)['total_bill'].sum()['Male', 'Lunch']

np.float64(595.6)

In [75]:
df.groupby(['sex', 'time'], observed = True)['total_bill'].sum()

sex     time
Male    Lunch      595.60
        Dinner    2661.22
Female  Lunch      571.87
        Dinner     999.08
Name: total_bill, dtype: float64

In [76]:
df.select_dtypes

<bound method DataFrame.select_dtypes of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>